# Generated by Django 3.1.1 on 2020-09-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目信息', 'verbose_name_plural': '项目信息'},
        ),
    ]
